### ISSUE TITLE
Add SerializerInfo attr to estimate complexity and features of various ser technologies

### ISSUE THREAD

**Issue by itadapter** [aumcode/serbench#15]

**Comment by itadapter** [comment]
Added SerializerInfo attribute. Now need to harvest data about other serializers and apply this attribute appropriately

**Comment by leo-gan** [comment]
Added SerializerInfo attributes to all serializers. Two parameters are not filled up yet: LinesOfCodeK = 0,  
     DataTypes = 0. Not sure I can do this without time consuming manual counting.
