### ISSUE TITLE
Need simplified OVERVIEW of TEST RESULTS/SUMMARY

### ISSUE THREAD

**Issue by binfomater** [aumcode/serbench#2]
I see the JSOn or CSV dump, but I'd like to see a more condensed overview.
Otherwise it will take forever to parse the CSV in Excel every time

**Comment by itadapter** [comment]
I am thinking about  a reporting tool that will suck the JSON output in.
Also maybe dump another Rowset that has summaries?

**Comment by itadapter** [comment]
We have decided to add Source/Serbench/WebViewer, it will create a package (a folder) on disk that will have all artifacts (css, js, htmls) to visualize the data. This way we don't spend time on outdated technologies (such as winforms) for visualization. The scripts are coming from NFX.Wave.dll.
The HTMLS are dynamically generated by the process, so it is possible to control what gets output etc..
