### ISSUE TITLE
Report formating issues

### ISSUE THREAD

**Issue by leo-gan** [aumcode/serbench#21]
I consider these issues as common issues. It would be nice if those issues were not repeated in all reports.
- "duration (ticks):    2,186.5" - Ticks are long type, they cannot have digits after point.
- any "470,857.86666666664" - now we don't have numbers which should be shown with ".86666666664" part. Rounding would be nice
- Now the columns are wide and almost all column can be narrowed to 1/3 of width. It is because of the header row, which keeps words like "Serbench.Specimens.Serializers.ServiceStackJsonSerializer.." Browser cannot break a line with this word (without spaces) to several lines. Maybe it makes sense to add spaces before dots? Like "Serbench .Specimens .Serializers .ServiceStackJsonSerializer..". This brings much more information to a single screen.
- When we scroll reports left-right up-down, it is hard to remember column and row headers. Maybe it makes sense to add the short serializer and test names to each cell in report? Say Serbench.Specimens.Serializers.ServiceStackJsonSerializer => ServiceStackJsonSerializer  ; Serbench.StockTests.SimpleDictionaryStringObject SimpleDict(10,10) => SimpleDict(10,10)

**Comment by sergey-msu** [comment]
Thank you for your remarks! I'll fix it in a day or two.

**Comment by itadapter** [comment]
Sergey, please proceed as we discussed today:
a. Column and row headers should be fixed
b. The rolled-up numbers should not show a decimal fraction part (not needed)
c. Remove ticks from the report, they cause overflow and show incorrect results, keep MS
d. Add "First exception" from dataset - to see what caused the break in execution
e. I would try using smaller font, to fit more stuff

**Comment by itadapter** [comment]
DONE
