### ISSUE TITLE
Errors leak to the overview-charts.htm

### ISSUE THREAD

**Issue by leo-gan** [aumcode/serbench#23]
If we have an error in comparing original object and an object after serialization -> deserialization (it is Assert on deser stage), this error detected only after deser stage. In this case we could (?) mark the whole test execution as fault, because we don't know when the error happened, on ser or deser stage. 
Right now, this error shown on the overview-table.htm report as red deser cell. But both, ser and deser cells, should be marked red. But more important, this error does not shown in the overview-charts.htm report and the bad data disturbs the whole beautiful picture. For example, now the JsonNET serializer is on the top on the Telemetry test (with 2B size payload :) ). This JsonNET marked on overview-table.htm with error on deser stage, but winner on overview-charts.htm.

**Comment by sergey-msu** [comment]
It should be fixed for sure. Thank you!

**Comment by itadapter** [comment]
So on the table report it will show green ser and red deser - this is all good.
However we fixed the charts (that only show one bar per ser/test) to EXCLUDE
cases that have failed deserialization.

DONE
