### ISSUE TITLE
Compilation fails with Win10 + VS2015

### ISSUE THREAD

**Issue by tomba** [aumcode/serbench#26]
I have a fresh installation of Win 10 and VS 2015 community edition (although I don't know if that's relevant as I haven't tried compiling before), and I'm not able to compile serbench. Serbench.Specimens fail to find any referenced assemblies, for some reason. I can also see in VS's UI that the assemblies cannot be found.

If I do the following, I can compile:

```
diff --git a/Source/Serbench.Specimens/Serbench.Specimens.csproj b/Source/Serbench.Specimens/Serbench.Specimens.csproj
index 816c483..5690418 100644
--- a/Source/Serbench.Specimens/Serbench.Specimens.csproj
+++ b/Source/Serbench.Specimens/Serbench.Specimens.csproj
@@ -144,15 +144,6 @@
     <Content Include="ThirdPartyLibs\Apolyton.FastJson.dll" />
   </ItemGroup>
   <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
-  <Import Project="$(SolutionDir)\.nuget\NuGet.targets" Condition="Exists('$(SolutionDir)\.nuget\NuGet.targets')" />
-  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
-    <PropertyGroup>
-      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
-    </PropertyGroup>
-    <Error Condition="!Exists('$(SolutionDir)\.nuget\NuGet.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)\.nuget\NuGet.targets'))" />
-    <Error Condition="!Exists('..\packages\Bond.CSharp.3.0.7\build\Bond.CSharp.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Bond.CSharp.3.0.7\build\Bond.CSharp.props'))" />
-    <Error Condition="!Exists('..\packages\Bond.CSharp.3.0.7\build\Bond.CSharp.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Bond.CSharp.3.0.7\build\Bond.CSharp.targets'))" />
-  </Target>
   <Import Project="..\packages\Bond.CSharp.3.0.7\build\Bond.CSharp.targets" Condition="Exists('..\packages\Bond.CSharp.3.0.7\build\Bond.CSharp.targets')" />
   <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
        Other similar extension points exist, see Microsoft.Common.targets.
```

**Comment by leo-gan** [comment]
Hi Tomi,

Try to "Enable NuGet Package Restore" on solution. Please, let me know if
it helps or not.

"....This project references NuGet package(s) that are missing on this
computer. Enable NuGet Package Restore to download them..."

On Mon, Aug 3, 2015 at 9:09 AM, Tomi Valkeinen notifications@github.com
wrote:

> This project references NuGet package(s) that are missing on this
> computer. Enable NuGet Package Restore to download them. For more
> information, see http://go.microsoft.com/fwlink/?LinkID=322105. The
> missing file is {0}.

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/

**Comment by itadapter** [comment]
Yeah, I had the same prob. Enabled NUGET to get all the good stuff which is referenced

**Comment by tomba** [comment]
I think the package restore is enabled by default on VS2015. The packages are downloaded, but the project fails to reference them. And not only the assemblies from nuget fail to be referenced, also System.\* assemblies are not found.

I'm guessing that something in those lines I removed above messes up the project's assembly search paths, or such.

**Comment by itadapter** [comment]
Take the code from release TAG, not the master branch

**Comment by tomba** [comment]
v1.1 fails the same way. Are you using VS2015 or earlier?

**Comment by itadapter** [comment]
2012

**Comment by wmjordan** [comment]
Perhaps it is because the absence of the packages.config file.

**Comment by cNoNim** [comment]
I updated packages and compile using VS2017, I think we can close this issue
